documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - ".readthedocs.yaml"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".pre-commit-config.yaml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"

examples:
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
