name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues and didn't find a similar request
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve or the use case
      placeholder: |
        I'm trying to do X but currently there's no way to...

        OR

        When fitting distributions to Y type of data, I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        I'd like a new parameter/method/class that allows...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How you envision using the feature
      render: python
      placeholder: |
        from spark_bestfit import DistributionFitter

        fitter = DistributionFitter(spark)
        # Example of how you'd use the new feature
        results = fitter.fit(df, "value", new_parameter=True)

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How significant is this feature for your use case?
      options:
        - "High - Blocking my use case"
        - "Medium - Would significantly improve my workflow"
        - "Low - Nice to have"
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How large do you estimate this change to be?
      options:
        - "Small - Minor change or addition"
        - "Medium - New feature with moderate complexity"
        - "Large - Significant new functionality or architectural change"
        - "Not sure"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: |
        - I tried doing X but it doesn't work because...
        - Workaround Y is possible but inefficient because...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or screenshots
      placeholder: |
        - Related to feature in library X
        - Paper/reference: ...
        - Screenshots: ...
